# Generated by Django 4.1.6 on 2023-08-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=25)),
                ("precipitation", models.IntegerField()),
                ("station_name", models.CharField(max_length=25)),
                ("max_temp", models.IntegerField()),
                ("min_temp", models.IntegerField()),
            ],
            options={
                "unique_together": {("date", "station_name")},
            },
        ),
        migrations.CreateModel(
            name="Statistics_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_max_temp", models.IntegerField()),
                ("avg_min_temp", models.IntegerField()),
                ("date", models.CharField(max_length=20)),
                ("station_name", models.CharField(max_length=25)),
                ("total_acc_ppt", models.IntegerField()),
            ],
            options={
                "unique_together": {("date", "station_name")},
            },
        ),
    ]
